import math
import torch
import tiktoken
import torch.nn as nn
import torch.nn.functional as F


config = {
    "vocab_size" : 50257,
    "emb_dim" : 768,
    "n_layers" : 12,
    "n_heads" : 32,
    "dropout_rate": 0.2,
    "context_size" : 1024,
    "qkv-bias": False
    }


class LinearNorm(nn.Module):
    def __int__(self):
        pass

class GELU(nn.Module):
    def forward(self,x):
        return 0.5*x*(
            1 + torch.tanh(
                math.sqrt(2.0 / math.pi)*(
                x + 0.044715*torch.pow(x,3)
            ))
            )
        

class MHA(nn.Module):
    def __init__(self, config):
        super().__init__()
        self.head_dim = config["emb_dim"] // config["n_heads"]
        self.n_heads = config["n_heads"]
        self.W_q = nn.Linear(config["emb_dim"], config["emb_dim"], bias=config["qkv-bias"])
        self.W_k = nn.Linear(config["emb_dim"], config["emb_dim"], bias=config["qkv-bias"])
        self.W_v = nn.Linear(config["emb_dim"], config["emb_dim"], bias=config["qkv-bias"])
        self.out_proj = nn.Linear(config["emb_dim"], config["emb_dim"])
        self.dropout = nn.Dropout(config["dropout_rate"])
        self.register_buffer('mask', torch.triu(torch.ones(config["context_size"], config["context_size"]), diagonal=1))

    def forward(self,X):
        b,T,emb_dim = X.shape
        Q = self.W_q(X)
        K = self.W_k(X)
        V = self.W_v(X)

        ### unroll the Q,K,V from b,T,emb_dim => b,T,n_heads,head_dim
        Q = Q.view(b,T,self.n_heads, self.head_dim)
        K = K.view(b,T,self.n_heads, self.head_dim)
        V = V.view(b,T,self.n_heads, self.head_dim)

        Q = Q.transpose(1, 2)
        K = K.transpose(1, 2)
        V = V.transpose(1, 2)

        att = Q @ K.transpose(-2, -1)
        att = att / math.sqrt(self.head_dim)

        att = att.masked_fill(
            self.mask[:T, :T].bool(),
            float("-inf")
        )

        att = torch.softmax(att, dim=-1)

        context = att @ V
        context = context.transpose(1, 2).contiguous()
        context = context.view(b, T, emb_dim)
        return context

class TransformerBlock(nn.Module):
    def __init__(self, config):
        super().__init__()
        self.mha =MHA(config)
        self.ln1 = nn.LayerNorm(config["emb_dim"])
        self.ln2 = nn.LayerNorm(config["emb_dim"])
        self.dropout = nn.Dropout(config["dropout_rate"])
        self.ffn = nn.Sequential(
            nn.Linear(config["emb_dim"], 4*config["emb_dim"]),
            GELU(),
            nn.Linear(4*config["emb_dim"], config["emb_dim"])
        )

    def forward(self,x):
        shortcut = x
        x = self.ln1(x)
        x = self.mha(x)
        x = self.dropout(x)
        x = x + shortcut          

        shortcut = x
        x = self.ln2(x)
        x = self.ffn(x)
        x = self.dropout(x)
        x = x + shortcut          
        return x
        

class GPT(nn.Module):
    def __init__(self,config):
        super().__init__()
        self.wte = nn.Embedding(config['vocab_size'], config['emb_dim'])
        self.pte = nn.Embedding(config['context_size'], config['emb_dim'])
        self.trf_blocks = nn.Sequential(*[TransformerBlock(config) for _ in range(config["n_layers"])])
        self.finalNorm = nn.LayerNorm(config['emb_dim'])
        self.final_head = nn.Linear(config['emb_dim'], config['vocab_size'], bias=False)
        
    
    def forward(self,x):
        _,T = x.shape
        tok_enc = self.wte(x)
        pos_enc = self.pte(torch.arange(T))
        x = tok_enc + pos_enc
        logits = self.trf_blocks(x)
        logits = self.finalNorm(logits)
        logits = self.final_head(logits)
        return logits


# tokenizer = tiktoken.get_encoding("gpt2")
# input_text = "Every effort moves you"
# input_token = tokenizer.encode(input_text)

# ## creating batch of this input
# batch_input = torch.tensor([input_token])

# gpt = GPT(config)
# output = gpt.forward(batch_input)

### token generate by model
# outputx = torch.argmax(output,dim=-1)
# print(tokenizer.decode(outputx.numpy()[0]))

# ### last token generated by modal
# output_last = output[:,-1,:]
# last_token = torch.argmax(output_last, -1)
# print(tokenizer.decode([last_token]))

